### PR TITLE
Fixed Minimize to tray #7

### PR DESCRIPTION
**Pull request by renatn**
Please review!

### CODE REVIEW

**Comment by 4ndv** [comment]
Needs option for changing behavior between minimizing and closing app, i think.

**Comment by antelle** [comment]
Such default behaviour will bother users. I agree with @4ndv, this should be optional (but for now, there's no infrastructure to save options to main process). I'll add options engine and then merge this as a checkbox in settings, thank you!

**Comment by 4ndv** [comment]
Should auto-logout when minimizing to tray.

**Comment by antelle** [comment]
So, I've implemented saving settings from webpage to app; now, the only blocker is locking (ux and flow): for now, only close is implemented.

**Comment by renatn** [comment]
:thumbsup:

**Comment by antelle** [comment]
So far, it has been merged to develop in 7df0328e1dfce93f41f70d0b59ecb4dfa9625fc9.
Changes I've made:
- lock on minimize
- minimize only on Windows (on Mac OSX, it's uncommon)
- checkbox in app settings

Will be available in upcoming v0.4.
Thanks for contribution!

**Pull request closed without merging**
